### ISSUE TITLE
Yosemite support

### ISSUE THREAD

**Issue by Mehonoshin** [rowanj/gitx#390]
Hi, folks!

I'm having issue with GitX on Yosemite(10.10). When running gitx in terminal, I recieve "Unable to open GitX.app".

Anybody has same problem?

PS: I'm not an Obj-C developer, so can't fix it by myself

UPD: when you already start gitx, then you can run gitx in terminal. In other cases it does not start

**Comment by lossius** [comment]
I just tested, and it works fine here. Did you try running the "Enable Terminal Usage..." from the Gitx menu again after upgrading to 10.10?

**Comment by Mehonoshin** [comment]
Yes, I did it.
The binary exists at /usr/local/bin/gitx

**Comment by elDub** [comment]
I am experiencing the same thing.  Both the inability to START gitx from the command line (yes, I tried re-executing "Enable Terminal Usage..."), and the absence of the error when gitx is already running.  Not a show-stopper, but a lost convenience from prior to Yosemite.

**Comment by elDub** [comment]
I think it has something to do with tmux, at least for me it does.  I cannot execute it within a tmux session, however in just a basic terminal window it does work.

**Comment by Mehonoshin** [comment]
@elDub is right, I've just tested, this issue exists only when you start gitx from tmux session

**Comment by atuttle** [comment]
Crashing for me on Yosemite, too. I can't get to the "enable terminal usage" checkbox because it crashes almost instantly after opening it -- regardless if I open from CLI or applications folder. :(

**Comment by rowanj** [comment]
This was probably due to #391, fixed in 0.15.1964 available now via in-app update and imminently via all the usual download links.

If you want to get the app to launch enough for in-app updates, temporarily turn on System Preferences -> General -> Close windows when quitting applications  to stop the window restore from crashing the app immediately upon startup.

**Comment by rowanj** [comment]
Once you've got the update, I expect you will be able to enable terminal usage as expected.

**Comment by Mehonoshin** [comment]
Still getting this issue after update and enabling terminal usage :(

**Comment by atuttle** [comment]
0.15.1964 isn't tagged or available on the releases page, and the "close windows when quitting applications" option doesn't work for me (maybe it doesn't apply to crashes?) Is there another place to download the latest build?

**Comment by rowanj** [comment]
I'll update the releases page now, but the latest build is available here:
*\* edit, wrong link
http://builds.phere.net/GitX/development/GitX-dev-1964.dmg

**Comment by CleanCut** [comment]
I didn't realize tmux was the problem!  I am also hitting this issue in tmux, but I always use tmux...

I just tried version dev-1964 and it didn't change anything in my case.

``` bash
$ gitx --version
GitX version 0.15.1964 ((null))
Using git found at /usr/bin/git, version 1.9.3 (Apple Git-50)
$ gitx
Unable to open GitX.app
```

**Comment by dsvensson** [comment]
Using .1964 on Yosemite, getting crash when opening my git repository,

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error enumerating commits'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff8862f64c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff8bc426de objc_exception_throw + 43
2   CoreFoundation                      0x00007fff8862f42a +[NSException raise:format:arguments:] + 106
3   Foundation                          0x00007fff942925b9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
4   GitX                                0x000000010b0b91f4 -[PBGitRevList addCommitsFromEnumerator:inPBRepo:] + 998
5   GitX                                0x000000010b0b79d1 -[PBGitRevList beginWalkWithSpecifier:] + 181
6   Foundation                          0x00007fff94207b7a __NSThread__main__ + 1345
7   libsystem_pthread.dylib             0x00007fff8d8cb2fc _pthread_body + 131
8   libsystem_pthread.dylib             0x00007fff8d8cb279 _pthread_body + 0
9   libsystem_pthread.dylib             0x00007fff8d8c94b1 thread_start + 13
```
